# Generated by Django 3.2.6 on 2021-08-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
