# Generated by Django 3.2.6 on 2021-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0002_delete_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(default=0)),
                ('tag_name', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('อยู่', 'อยู่'), ('ไม่อยู่', 'ไม่อยู่')], default='อยู่', max_length=20)),
            ],
        ),
    ]
