# Generated by Django 3.2.6 on 2021-08-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='tag_name',
            new_name='object_name',
        ),
    ]
